DROP TABLE IF EXISTS variables;
DROP TABLE IF EXISTS zone;
DROP TABLE IF EXISTS soa;
DROP TABLE IF EXISTS a;
DROP TABLE IF EXISTS aaaa;
DROP TABLE IF EXISTS ns;
DROP TABLE IF EXISTS cname;
DROP TABLE IF EXISTS hinfo;
DROP TABLE IF EXISTS txt;
DROP TABLE IF EXISTS mx;
DROP TABLE IF EXISTS rr;
DROP TABLE IF EXISTS ptr;

CREATE TABLE variables(name VARCHAR(64) NOT NULL, val VARCHAR(64) NOT NULL, PRIMARY KEY(name));
INSERT INTO variables(name, val) VALUES('db_version', '1');

CREATE TABLE zone (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, PRIMARY KEY(id), UNIQUE(name));
CREATE TABLE soa  (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, ttl INT UNSIGNED, refresh INT UNSIGNED, serial INT UNSIGNED, retry INT UNSIGNED, expire INT UNSIGNED, minimum INT UNSIGNED, email VARCHAR(63) NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), PRIMARY KEY(id), UNIQUE(name));
CREATE TABLE a    (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, ttl INT UNSIGNED, address VARCHAR(12) NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), PRIMARY KEY(id), INDEX(name));
CREATE TABLE aaaa (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, ttl INT UNSIGNED, address VARCHAR(39) NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), PRIMARY KEY(id), INDEX(name));
CREATE TABLE ns   (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, ttl INT UNSIGNED, host VARCHAR(255) NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), PRIMARY KEY(id), INDEX(name));
CREATE TABLE cname(id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, ttl INT UNSIGNED, host VARCHAR(255) NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), PRIMARY KEY(id), INDEX(name));
CREATE TABLE hinfo(id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, ttl INT UNSIGNED, cpu VARCHAR(255) NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), host VARCHAR(255) NOT NULL, PRIMARY KEY(id), INDEX(name));
CREATE TABLE txt  (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, ttl INT UNSIGNED, data VARCHAR(255) NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), PRIMARY KEY(id), INDEX(name));
CREATE TABLE mx   (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, ttl INT UNSIGNED, host VARCHAR(255) NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), preference INT UNSIGNED NOT NULL DEFAULT 10, PRIMARY KEY(id), INDEX(name));
CREATE TABLE rr   (id INT UNSIGNED NOT NULL AUTO_INCREMENT, data VARBINARY(255) NOT NULL, ttl INT UNSIGNED, class INT UNSIGNED NOT NULL, `type` INT UNSIGNED NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), PRIMARY KEY(id), INDEX(name));
CREATE TABLE ptr  (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, ttl INT UNSIGNED, host VARCHAR(255) NOT NULL, zone_id INT NOT NULL REFERENCES zone(id), PRIMARY KEY(id),INDEX(name));
