.TH nsadmin 8
.SH NAME
nsadmin \- DNS server administration utility
.SH SYNOPSIS
.br
.TP
.B nsadmin options
.br
.PP
.br
.SH DESCRIPTION
DNS server administration utility
.SH SUPPORT
Visit official web page on http://dns4j.sourceforge.net
.SH SEE ALSO
.B dns4j.conf(5), nsdaemon(8), nsclient(8)
.SH AUTHOR
Lorenzo Ingrilli' <info@lorenzoingrilli.it>
.SH COPYRIGHT
Lorenzo Ingrilli' <info@lorenzoingrilli.it>
.PP