.TH nsdaemon 8
.SH NAME
nsdaemon \- DNS server
.SH SYNOPSIS
.br
.TP
.B nsdaemon [-c config-file]
.br
.PP
.br
.SH DESCRIPTION
DNS4J is a DNS Server implementation.
.SH OPTIONS
.TP                           
.B -c config-file
.br
Use config-file as the configuration file instead of the default, /etc/dns4j/dns4j.conf
.PP
.SH FILES
.TP                           
.B /etc/dns4j/dns4j.conf
.br
The default configuration file
.br
.SH SUPPORT
Visit official web page on http://dns4j.sourceforge.net
.SH SEE ALSO
.B dns4j.conf(5), nsadmin(8), nsclient(8)
.SH AUTHOR
Lorenzo Ingrilli' <info@lorenzoingrilli.it>
.SH COPYRIGHT
Lorenzo Ingrilli' <info@lorenzoingrilli.it>
.PP