.TH dns4j.conf 5
.SH NAME
dns4j.conf - DNS4J configuration file
.SH SYNOPSIS
.B /etc/dns4j/dns4j.conf
.SH DESCRIPTION
todo
.SH FILES
/etc/dns4j/dns4j.conf
.SH SUPPORT
Visit official web page on http://dns4j.sourceforge.net
.SH SEE ALSO
.B nsdaemon(8), nsadmin(8), nsclient(8)
.SH AUTHOR
Lorenzo Ingrilli' <info@lorenzoingrilli.it>
.SH COPYRIGHT
Lorenzo Ingrilli' <info@lorenzoingrilli.it>
.PP