CREATE DATABASE IF NOT EXISTS dns4j;

CREATE TABLE IF NOT EXISTS soa(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(63) NOT NULL,
	ttl UNSIGNED INT,
	refresh UNSIGNED INT,
	serial UNSIGNED INT,
	retry UNSIGNED INT,
	expire UNSIGNED INT,
	minimum UNSIGNED INT,
	email VARCHAR(63),
	PRIMARY KEY(id),
	UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS a(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(63) NOT NULL,
	ttl UNSIGNED INT,
	address VARCHAR(12) NOT NULL,
	PRIMARY KEY(id),
	INDEX(name)
);

CREATE TABLE IF NOT EXISTS aaaa(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(63) NOT NULL,
	ttl UNSIGNED INT,
	address VARCHAR(64) NOT NULL,
	PRIMARY KEY(id),
	INDEX(name)
);

CREATE TABLE IF NOT EXISTS ns(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(63) NOT NULL,
	ttl UNSIGNED INT,
	nsdname VARCHAR(63) NOT NULL,
	PRIMARY KEY(id),
	INDEX(name)
);

CREATE TABLE IF NOT EXISTS cname(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(63) NOT NULL,
	ttl UNSIGNED INT,
	cname VARCHAR(63) NOT NULL,
	PRIMARY KEY(id),
	INDEX(name)
);

CREATE TABLE IF NOT EXISTS hinfo(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(63) NOT NULL,
	ttl UNSIGNED INT,
	cpu VARCHAR(63) NOT NULL,
	host VARCHAR(63) NOT NULL,
	PRIMARY KEY(id),
	INDEX(name)
);

CREATE TABLE IF NOT EXISTS txt(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(63) NOT NULL,
	ttl UNSIGNED INT,
	data VARCHAR(256) NOT NULL,
	PRIMARY KEY(id),
	INDEX(name)
);

CREATE TABLE IF NOT EXISTS mx(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(63) NOT NULL,
	ttl UNSIGNED INT,
	exchange VARCHAR(63) NOT NULL,
	preference UNSIGNED INT NOT NULL DEFAULT 10, 
	PRIMARY KEY(id),
	INDEX(name)
);

CREATE TABLE IF NOT EXISTS ptr(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(68) NOT NULL,
	ttl UNSIGNED INT,
	ptrdname VARCHAR(63) NOT NULL,
	PRIMARY KEY(id),
	INDEX(name)
);

CREATE TABLE IF NOT EXISTS rr(
	id UNSIGNED INT AUTO_INCREMENT,
	name VARCHAR(63) NOT NULL,
	ttl UNSIGNED INT,
	data VARBINARY(256) NOT NULL,
	PRIMARY KEY(id),
	INDEX(name)
);
